name: CI for Anaconda

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: '3.8'  # Especifica la versión de Python que necesitas

    - name: Create and activate conda environment
      run: |
        conda env create -f environment.yml
        conda activate myenv  # Cambia "myenv" por el nombre de tu entorno definido en environment.yml

    - name: Verify environment
      run: conda list

    - name: Clean up
      if: always()
      run: conda remove --name myenv --all
