name: CI for Anaconda

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: '3.8'  # Especifica la versión de Python que necesitas

    - name: Initialize Conda
      run: conda init bash

    - name: Create and activate conda environment
      shell: bash -l {0}
      run: |
        conda create --name myenv python=3.8 -y
        conda activate myenv

    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda install numpy pandas scikit-learn -y  # Agrega más paquetes si es necesario

    - name: Verify environment
      shell: bash -l {0}
      run: conda list


    - name: Clean up
      if: always()
      shell: bash -l {0}
      run: conda remove --name myenv --all -y
