name: CI for Java with Dependency Check

on:
  push:
    branches:
      - develop  # Cambiar a 'develop' en lugar de 'main'
  pull_request:
    branches:
      - develop  # Cambiar a 'develop' en lugar de 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'  # Puedes cambiar a la versión que necesites

      - name: Install dependencies and build with Maven
        run: |
          mvn clean install

      - name: Check if specific dependencies are installed
        run: |
          if mvn dependency:tree | grep -q 'org.springframework:spring-core' && mvn dependency:tree | grep -q 'org.junit.jupiter:junit-jupiter-api'; then
            echo "Dependencies already installed"
          else
            echo "Dependencies not found, installing..."
            mvn install:install-file -Dfile=path/to/spring-core.jar -DgroupId=org.springframework -DartifactId=spring-core -Dversion=5.3.0 -Dpackaging=jar
            mvn install:install-file -Dfile=path/to/junit-jupiter-api.jar -DgroupId=org.junit.jupiter -DartifactId=junit-jupiter-api -Dversion=5.7.1 -Dpackaging=jar
          fi
          
      - name: Run tests with Maven
        run: mvn test

            echo "Dependencies already installed"
          else
            echo "Dependencies not found, installing..."
            pip install Flask requests
          fi
