name: CI for Python with Dependency Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install pytest

      - name: Check if specific dependencies are installed
        run: |
          if pip show Flask && pip show requests; then
            echo "Dependencies already installed"
          else
            echo "Dependencies not found, installing..." 
            pip install Flask requests
