name: CI for Go

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.21' # Cambia a la versión que necesites

    - name: Create and Run Go Test
      run: |
        mkdir -p myapp
        cd myapp
        echo 'package main\nimport "testing"\nfunc TestSample(t *testing.T) {}' > main_test.go
